############################# USAGE   ############################
####    ansible-playbook V-204392.yml -e target=all -kK        ###
##################################################################
---
- name: Check and Remediate STIG Finding V-204392
  hosts: "{{ target }}"
  become: yes
  tasks:
      - name: ensure an empty file exist 
        file: 
          path: /tmp/files_perm.txt
          state: touch 
        delegate_to: localhost

      - name: Generate list of files
        shell: >
           for i in `rpm -Va | grep -E '^.{1}M|^.{5}U|^.{6}G' | cut -d " " -f 4,5`;do for j in `rpm -qf $i`;do rpm -ql $j --dump | cut -d " " -f 1,5,6,7 | grep $i;done;done | awk '{print $1}'
        register: files
      
      - debug:
         var: files.stdout_lines

      - name: ls -l 
        shell: ls -l {{ item }}
        loop: "{{ files.stdout_lines }}"
        register: perm_list

      - name: Display perms 
        debug: 
          msg: "{{ perm_list.results | map(attribute='stdout') }}"

      - name: Print output to a file
        copy:
          content: "{{ perm_list.results | map(attribute='stdout' ) | join('\n')  }}"
          dest: /tmp/files_perm.txt
        delegate_to: localhost
      
      - name: Get packages with incorrect file permissions or ownership
        shell: |
            rpm -Va --nolinkto --nofiledigest --nosize --nomtime --nodigest --nosignature | grep -E '^(.M|.....U|......G)' | tee /dev/stderr | cut -c13- | sed 's/^ //' | xargs rpm -qf --qf='%{name}\n' | sort -u
        register: pkg_list

      - name: Display output
        debug:
          msg: "{{ pkg_list.stdout_lines }}"

      - name: Reset file permissions/ownership to vendor values
        shell: "rpm {{ item[0] }} {{ item[1] }}" 
        changed_when: false
        register: Perm_fixed
        with_nested:
           - ['--setperms', '--setugids']
           - "{{ pkg_list.stdout_lines | default([]) }}"

      - name: Display error during remediation
        debug:
            msg: "{{ item.stdout_lines }}"
        changed_when: true
        with_items: "{{ Perm_fixed.results }}"
        when:
            - Perm_fixed is changed
            - item is failed